use_frameworks!

platform :ios, '8.0'

target 'YCYearMonthDatePicker_Example' do
  pod 'YCYearMonthDatePicker', :path => '../'

  target 'YCYearMonthDatePicker_Tests' do
    inherit! :search_paths

    
  end
end
